### ISSUE TITLE
error in terminal when cloning the git

### ISSUE THREAD

**Issue by UmbraVivens** [strohitv/splatnet3-token-util#6]
i'm not savvy about git, this happened when trying to run the clone command through cmd.exe, and i don't know what to do about it.

<img width="707" height="167" alt="Image" src="https://github.com/user-attachments/assets/4022b317-9fed-47ed-8ad5-c11df274d983" />

**Comment by strohitv** [comment]
Hi!

This error means the following:
When trying to download splatnet3-token-util, github asks you who you are. The "identity" / "password" you are using to answer with "I am UmbraVivens" is stored on your computer at this path: `C:\Users\<USERNAME>\.ssh`.

However, this identity stored there is not registered for your github account so the question cannot be answered succesfully and github denies access (even though it's a public repository).

There are two ways to solve this:
 
 
## 1. Add your ssh key to github.
There are plenty instructions on the internet, for example [this official one from github](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account?platform=windows)

With this way, you "connect" the git application on your computer to your github account so that github knows downloads to your computer were made by your account.

## 2. Use the alternative way (https)
This option does not ask for your identity as long as you're only downloading public projects. This can be done with these commands:
```bash
# download splatnet3-token-util
git clone https://github.com/strohitv/splatnet3-token-util.git

# download s3s (if necessary) 
git clone https://github.com/frozenpandaman/s3s.git
```
Notice how the two links in the commands are different, they start with `https://` instead of `git@github.com:`.

If you ever try to do something which requires github to know who you are while using this method, you'll be prompted to enter your github username and password.

---

I hope this helps! If further questions arise, feel free to ask them here!

**Comment by UmbraVivens** [comment]
oh thank you, i'm past this step now, however...
after setting up the AVD and trying to run `python main.py`, i get the following error

<img width="979" height="512" alt="Image" src="https://github.com/user-attachments/assets/f7663b27-c6e3-4bb8-84c9-cedb78fd25c7" />

**Comment by strohitv** [comment]
`pip install -r requirements.txt`

**Comment by UmbraVivens** [comment]
<img width="979" height="512" alt="Image" src="https://github.com/user-attachments/assets/956e0bf3-f594-4fcb-994e-7ef8f2c34853" />

**Comment by strohitv** [comment]
Your python version is too old.
Please update to `python 3.11.0` or newer

**Comment by strohitv** [comment]
Hey, sorry for the late response.
In the `config/config.json` file as well as the `config_run_s3s.json` file, please write paths with two backslashes `\\` instead of one `\`.

For example:
- bad: `C:\users\some-user`
- correct: `C:\\users\\some-user`

This should fix this issue.

**Comment by strohitv** [comment]
> I'm sure there is a quicker way to do this, but what worked for me was to run the exec, and install each package module individually with each error that pops up, rinse and repeat til I had everything.
> 
> In your case its telling you to install BeautifulSoup4, so it'd be: `pip install BeautifulSoup4`.
> 
> From what I remember a few of the package modules you need are: `image/imagehash` `multiprocess` `uncurl` `numpy`
> 
> Just open the file in Notepad++ from each designated path/line listed in the console, it basically tells you what you have missing.

I think I understand now what's wrong. An update is on the way.

**Comment by UmbraVivens** [comment]
hello, after updating, i still get the error

<img width="979" height="512" alt="Image" src="https://github.com/user-attachments/assets/f5b5582f-1a5a-4e8e-8de1-90a8f70a75dc" />

**Comment by strohitv** [comment]
> Hey, sorry for the late response. In the `config/config.json` file as well as the `config_run_s3s.json` file, please write paths with two backslashes `\\` instead of one `\`.
> 
> For example:
> 
>     * bad: `C:\users\some-user`
> 
>     * correct: `C:\\users\\some-user`
> 
> 
> This should fix this issue.

You'll need to do this.

**Comment by UmbraVivens** [comment]
sorry it's already like that, i've never touched that file after the initial setup when i had to add my AVD name into it

<img width="824" height="767" alt="Image" src="https://github.com/user-attachments/assets/7ba9f27e-6256-486c-9dd1-50d7da0f208c" />

**Comment by strohitv** [comment]
Have you also checked the `config_run_s3s.json` file which is in the same folder as the `run_s3s.py` file?

**Comment by UmbraVivens** [comment]
> Have you also checked the `config_run_s3s.json` file which is in the same folder as the `run_s3s.py` file?

thank you, that one lacked double backslashes, and now it's fixed
however... now i get this

<img width="979" height="512" alt="Image" src="https://github.com/user-attachments/assets/69f1ff80-ba7c-4057-9c30-300535d51eb3" />

it says it can't find python for some reason

**Comment by strohitv** [comment]
Go into `config_run_s3s.json` and replace `python3` with just `python`.

You also have to use `python run_s3s.py` like you would use s3s in general, for example:
```
python run_s3s.py --getseed
python run_s3s.py -r -M
```
